### ISSUE TITLE
ERR_INVALID_ARG_TYPE(name, 'string', value)

### ISSUE THREAD

**Issue by P-Vamshi-Seshasayan** [googleworkspace/md2googleslides#91]
I want to display the link of teh generated slides on a php page using the following code. slides.md is already there. It's working fine in the terminal but not in php.
$output=array();
exec('"/home/user/.npm-global/bin/md2gslides" slides.md --copy=1z3XLhVWc03U3deHy --title "Test Slide" --no-browser 2>&1', $output);
print_r($output);

Any help is appreciated.

Error:
Array
(
    [0] => internal/validators.js:125
    [1] =>     throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    [2] =>     ^
    [3] => 
    [4] => TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    [5] =>     at validateString (internal/validators.js:125:11)
    [6] =>     at Object.join (path.js:1147:7)
    [7] =>     at Object. (/home/user/.npm-global/lib/node_modules/md2gslides/bin/md2gslides.js:33:38)
    [8] =>     at Module._compile (internal/modules/cjs/loader.js:778:30)
    [9] =>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    [10] =>     at Module.load (internal/modules/cjs/loader.js:653:32)
    [11] =>     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    [12] =>     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    [13] =>     at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    [14] =>     at startup (internal/bootstrap/node.js:283:19)
    [15] =>     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
)

**Comment by jpoehnelt** [comment]
Closing this issue as the repository is archived.
